### ISSUE TITLE
OpenID Connect error thrown when disabled

### ISSUE THREAD

**Issue by Ssmidge** [iFargle/headscale-webui#10]
An error gets thrown when I try to load the main page, it happens when "oidc" is commented out in the headscale configuration file.

**Docker-compose:**

version: '3.5'
services:
  headscale:
    image: headscale/headscale:latest
    container_name: headscale
    volumes:
      - ./config:/etc/headscale
      - ./data/data:/var/lib/headscale
    ports:
      - 8080:8080
    command: headscale serve
    restart: unless-stopped
  headscale-webui:
    image: ghcr.io/ifargle/headscale-webui:latest
    container_name: headscale-webui
    depends_on:
      - headscale
    ports:
      - 5000:5000
    environment:
      - TZ=America/Toronto
      - HS_SERVER=[REDACTED]
      - BASE_PATH="/admin"
      - KEY="[REDACTED]"
    volumes:
      - ./volume:/data
      - ./config/:/etc/headscale/

**Log:**

headscale-webui    | 2023-02-10 21:24:24,628 - server - ERROR - Exception on /admin/ [GET]
headscale-webui    | Traceback (most recent call last):
headscale-webui    |   File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
headscale-webui    |     response = self.full_dispatch_request()
headscale-webui    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
headscale-webui    |   File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 1822, in full_dispatch_request
headscale-webui    |     rv = self.handle_user_exception(e)
headscale-webui    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
headscale-webui    |   File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
headscale-webui    |     rv = self.dispatch_request()
headscale-webui    |          ^^^^^^^^^^^^^^^^^^^^^^^
headscale-webui    |   File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
headscale-webui    |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
headscale-webui    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
headscale-webui    |   File "/app/server.py", line 39, in overview_page
headscale-webui    |     render_page = renderer.render_overview(),
headscale-webui    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
headscale-webui    |   File "/app/renderer.py", line 106, in render_overview
headscale-webui    |     if config_yaml["oidc"]:

**Comment by iFargle** [comment]
Should be good now.  v0.2.4 / latest.  Please test and let me know!

**Comment by Ssmidge** [comment]
It seems to work now but the page is missing CSS. 
![image](https://user-images.githubusercontent.com/43932476/218269809-2e40aa58-6b9a-4fad-a105-74fe4940755a.png)

**Comment by Ssmidge** [comment]
It seems like the issue is that the assets are being loaded from /admin/X instead of /X.

**Comment by Ssmidge** [comment]
I have resolved this issue by changing my proxy configuration, it seems like I had to change the base path of headscale-webui to "/" and proxy /admin to / (My headscale server is running on the root domain.)
