### ISSUE TITLE
Setup with the Linux bare metal installation of Headscale?

### ISSUE THREAD

**Issue by hagbrain21** [iFargle/headscale-webui#100]
Hi, how to setup headscale-webui when I setup Headscale with this guide: https://headscale.net/running-headscale-linux/

I dont get it, but is is necessary to setup Headscale as a Docker Container for the GUI to work?

Best regards,

Peter

**Comment by iFargle** [comment]
Yes. Headscale itself does not provide a GUI.  You will need both :)

On May 3, 2023 4:58:13 PM UTC, hagbrain21 ***@***.***> wrote:
>Hi, how to setup headscale-webui when I setup Headscale with this guide: https://headscale.net/running-headscale-linux/
>
>I dont get it, but is is necessary to setup Headscale as a Docker Container for the GUI to work?
>
>Best regards,
>
>Michael
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/iFargle/headscale-webui/issues/100
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Albert J. Copeland
***@***.***
PGP Fingerprint:  64F6C4EB46C4543A

**Comment by iFargle** [comment]
Oh sorry I didn't see bare metal
Basically all you'd need to do is follow what's in the Dockerfile (if you aren't using Docker) and replicate it bare metal, though this is not a supported config.

**Comment by hagbrain21** [comment]
So, how does it work when Docker and Headscale are on two different bare metals or virtual servers with different ip/etc. How can the webui Docker access the config and web storage? Sorry, Im not working with Docker that much.

**Comment by iFargle** [comment]
You wouldn't be able to access the headscale config file, so the Overview page will be broken.  That's the only place I use that.

Otherwise, all other info comes from the HS_SERVER environment variable.  You can manage everything as normal, just no Overview page (It may still render, but a lot of items will just say N/A)

**Comment by atb00ker** [comment]
I'm planning to make a PR soon, but in the meanwhile: https://github.com/atb00ker/headscale-webui should help you! 😄

**Comment by hagbrain21** [comment]
Works great. On Debian its little annoying to install Python 3.11 and poetry also not in repositories, but great work! Thanks.

**Comment by atb00ker** [comment]
>  little annoying to install Python 3.11 and poetry

Debian 12 is expected to be released in a couple of months and both are available in it's repository, so it's only a problem for the meanwhile! :smile:

**Comment by iFargle** [comment]
PR approved and merged :) Thank you!
