### ISSUE TITLE
WebUI Internal Server Error:

### ISSUE THREAD

**Issue by DrShurii** [iFargle/headscale-webui#121]
WebUI is not working anymore , i get Internal Server Error:

getting the below error :

headscale-webui | [2023-10-22 14:25:04,859] INFO in helper: All startup checks passed.
headscale-webui | [2023-10-22 14:25:04,860] ERROR in app: Exception on / [GET]
headscale-webui | Traceback (most recent call last):
headscale-webui | File "/app/.venv/lib/python3.11/site-packages/cryptography/fernet.py", line 133, in _verify_signature
headscale-webui | h.verify(data[-32:])
headscale-webui | File "/app/.venv/lib/python3.11/site-packages/cryptography/hazmat/primitives/hmac.py", line 70, in verify
headscale-webui | ctx.verify(signature)
headscale-webui | File "/app/.venv/lib/python3.11/site-packages/cryptography/hazmat/backends/openssl/hmac.py", line 84, in verify
headscale-webui | raise InvalidSignature("Signature did not match digest.")
headscale-webui | cryptography.exceptions.InvalidSignature: Signature did not match digest.
headscale-webui |
headscale-webui | During handling of the above exception, another exception occurred:
headscale-webui |
headscale-webui | Traceback (most recent call last):
headscale-webui | File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
headscale-webui | response = self.full_dispatch_request()
headscale-webui | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
headscale-webui | File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
headscale-webui | rv = self.handle_user_exception(e)
headscale-webui | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
headscale-webui | File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
headscale-webui | rv = self.dispatch_request()
headscale-webui | ^^^^^^^^^^^^^^^^^^^^^^^
headscale-webui | File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
headscale-webui | return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
headscale-webui | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
headscale-webui | File "/app/server.py", line 114, in decorated
headscale-webui | return view_func(*args, **kwargs)
headscale-webui | ^^^^^^^^^^^^^^^^^^^^^^^^^^
headscale-webui | File "/app/server.py", line 141, in overview_page
headscale-webui | pass_checks = str(helper.load_checks())
headscale-webui | ^^^^^^^^^^^^^^^^^^^^
headscale-webui | File "/app/helper.py", line 301, in load_checks
headscale-webui | if not key_check(): return 'settings_page'
headscale-webui | ^^^^^^^^^^^
headscale-webui | File "/app/helper.py", line 58, in key_check
headscale-webui | api_key = headscale.get_api_key()
headscale-webui | ^^^^^^^^^^^^^^^^^^^^^^^
headscale-webui | File "/app/headscale.py", line 66, in get_api_key
headscale-webui | decrypted_key = fernet.decrypt(enc_api_key).decode()
headscale-webui | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
headscale-webui | File "/app/.venv/lib/python3.11/site-packages/cryptography/fernet.py", line 90, in decrypt
headscale-webui | return self._decrypt_data(data, timestamp, time_info)
headscale-webui | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
headscale-webui | File "/app/.venv/lib/python3.11/site-packages/cryptography/fernet.py", line 151, in _decrypt_data
headscale-webui | self._verify_signature(data)
headscale-webui | File "/app/.venv/lib/python3.11/site-packages/cryptography/fernet.py", line 135, in _verify_signature
headscale-webui | raise InvalidToken
headscale-webui | cryptography.fernet.InvalidToken
headscale-webui | [2023-10-22 14:25:04 -0400] [8] [ERROR] Error handling request /favicon.ico
headscale-webui | Traceback (most recent call last):
headscale-webui | File "/app/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 136, in handle
headscale-webui | self.handle_request(listener, req, client, addr)
headscale-webui | File "/app/.venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 169, in handle_request
headscale-webui | resp, environ = wsgi.create(req, client, addr,
headscale-webui | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
headscale-webui | File "/app/.venv/lib/python3.11/site-packages/gunicorn/http/wsgi.py", line 183, in create
headscale-webui | path_info = path_info.split(script_name, 1)[1]
headscale-webui | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
headscale-webui | IndexError: list index out of range

**Comment by DrShurii** [comment]
problem solved

**Comment by smaartscz** [comment]
How did you solve it?

**Comment by DrShurii** [comment]
I had some issues with my docker-compose.yml file, I created a new one as below.

version: '3.5'
services:
  headscale:
    image: headscale/headscale:latest
    volumes:
      - ./config:/etc/headscale/
      - ./data:/var/lib/headscale
    ports:
      - **" your port "**:8080
    command: headscale serve
    restart: unless-stopped

  headscale-webui:
    image: ghcr.io/ifargle/headscale-webui:latest
    container_name: headscale-webui
    environment:
      - TZ=**" your timezone "**
      - COLOR=red                              # Use the base colors (ie, no darken-3, etc) -
      - HS_SERVER=**http://"IP:Port"**    # Reachable endpoint for your Headscale server
      - DOMAIN_NAME=**http://"IP:Port"**   # The base domain name for this container.
      - SCRIPT_NAME=/admin                     # This is your applications base path (wsgi requires the name "SCRIPT_NAME").  Remove if you are hosing at the root /
      - KEY=**" The generated key"**             # Generate with "openssl rand -base64 32" - used to encrypt your key on disk.
      - AUTH_TYPE=basic                         # AUTH_TYPE is either Basic or OIDC.  Empty for no authentication
      - LOG_LEVEL=info                         # Log level.  "DEBUG", "ERROR", "WARNING", or "INFO".  Default "INFO"
      # ENV for Basic Auth (Used only if AUTH_TYPE is "Basic").  Can be omitted if you aren't using Basic Auth
      - BASIC_AUTH_USER=**"Username for Webui"**                 # Used for basic auth
      - BASIC_AUTH_PASS=**"Password"**                  # Used for basic auth
      # ENV for OIDC (Used only if AUTH_TYPE is "OIDC").  Can be omitted if you aren't using OIDC
      #- OIDC_AUTH_URL=https://auth.$DOMAIN/.well-known/openid-configuration # URL for your OIDC issuer's well-known endpoint
      #- OIDC_CLIENT_ID=headscale-webui         # Your OIDC Issuer's Client ID for Headscale-WebUI
      #- OIDC_CLIENT_SECRET=YourSecretHere      # Your OIDC Issuer's Secret Key for Headscale-WebUI
    ports:
      - **"port"**:5000
    volumes:
      - ./volume:/data                         # Headscale-WebUI's storage.  Make sure ./volume is readable by UID 1000 (chown 1000:1000 ./volume)
      - ./config/:/etc/headscale/:ro # Headscale's config storage location.  Used to read your Headscale config.
    restart: unless-stopped
