### ISSUE TITLE
How to run it in the background?

### ISSUE THREAD

**Issue by appleimperio** [iFargle/headscale-webui#135]
Hi I installed as Bare Metal is there any way to run it in the background.? Thank You

**Comment by MartinJohannesNilsen** [comment]
> Hi I installed as Bare Metal is there any way to run it in the background.? Thank You

My tips is to run it as a service. Then, you could enable it on boot and start/stop/restart it at will. Another approach could be to utilize the linux package `screen`, where you could attach and detach the terminal running the application

**Comment by appleimperio** [comment]
Thanks I ended up using this command -D for daemon `poetry run gunicorn -D -b 0.0.0.0:5000 server:app`
