### ISSUE TITLE
Context location

### ISSUE THREAD

**Issue by henry-bao** [iFargle/headscale-webui#17]
Is setting context location still needed as it says in the README? Since the docker image is published in ghcr

**Comment by iFargle** [comment]
It is not -- I'll be updating the README in an hour or so with last nights changes 👍

**Comment by iFargle** [comment]
Updated.  Please pull v0.2.5/latest from GHCR 👍

**Comment by henry-bao** [comment]
Thanks for the update!

**Comment by iFargle** [comment]
Let me know if you have any troubles!  The Settings page has info on the git commit / version / build date.  As of right now the git commit is the same as current main.  If those don't match you may need to pull again.
