### ISSUE TITLE
Nginx documentations

### ISSUE THREAD

**Issue by henry-bao** [iFargle/headscale-webui#18]
It would be really helpful to also include a documentation for Nginx as well 😇

**Comment by iFargle** [comment]
@qiangyt tested this yesterday.  I'll get it added to the README today :) give me a few hours to get to a computer.

**Comment by iFargle** [comment]
It's in the README.  Give it a shot and let us know.

**Comment by henry-bao** [comment]
Awesome, I'll give it a go

**Comment by iFargle** [comment]
Re-open this issue if you have troubles.  Or start a new issue, doesn't matter.  I'll help where I can :)
