### ISSUE TITLE
Headscale path

### ISSUE THREAD

**Issue by henry-bao** [iFargle/headscale-webui#19]
https://github.com/iFargle/headscale-webui/blob/main/docker-compose.yml#L13
https://github.com/iFargle/headscale-webui/blob/main/Dockerfile#L46

I was wondering if the container path to headscale should be set to `/headscale` instead of `/etc/headscale` in the docker-compose file

**Comment by iFargle** [comment]
https://github.com/iFargle/headscale-webui/blob/main/renderer.py#L24

Should probably just update the Dockerfile with /etc/headscale -- I just picked this directory to mimic where Headscale server hosts its config files.  6 one way half a dozen the other, really

**Comment by henry-bao** [comment]
Sounds good, just letting you know. Since I saw it also created the `/headscale` volume on deployment
