### ISSUE TITLE
Test OIDC providers and add documentation

### ISSUE THREAD

**Issue by iFargle** [iFargle/headscale-webui#29]
Right now, Authelia has been tested as working.
I need help testing others.

**Comment by iFargle** [comment]
https://github.com/iFargle/headscale-webui/blob/0818d70543d89c62766fa786b3860bf5e2fe4f2f/server.py#L47

If you provide a valid well-known endpoint, other providers *should* work, but I don't have any to test.

**Comment by FredericIV** [comment]
Keycloak works out of the box!

**Headscale Side**
The keycloak endpoint can be found on the realm settings page as the "OpenID Endpoint Configuration" link.
```
OIDC_AUTH_URL = https://[DOMAIN]/realms/[REALM]/.well-known/openid-configuration
OIDC_CLIENT_ID=Headscale-WebUI
OIDC_CLIENT_SECRET=secret
AUTH_TYPE=oidc
```
**Keycloak Side**
```
Client ID = Headscale-WebUI
Callback URI = https://[DOMAIN]/[SCRIPT_NAME]/oidc_callback
Client Authentication (Previously called confidential access or similar) = True
Client Secret = secret
```
All other settings default

**Comment by iFargle** [comment]
Awesome, glad to know!  I'll update the README!  Thanks!

**Comment by iFargle** [comment]
Added Keycloak docs to SETUP.md. Thanks! 👍

**Comment by iFargle** [comment]
Added to docs!
