### ISSUE TITLE
Failure to redirect properly when key.txt is empty or missing

### ISSUE THREAD

**Issue by FredericIV** [iFargle/headscale-webui#30]
# Observation
When key.txt is empty: headscale-webui serves a redirect loop on whichever page. When key.txt is missing: the console reports the lack of key; the browser is continuously redirected to /prefix/settings, even when on /prefix/settings.

# Replication
- Delete key.txt
or
- Empty key.txt

# Tested conditions
- With OIDC auth
- With BASIC auth

# User mitigation
Use the python console to manually encode the api key.
```python3
from cryptography.fernet import Fernet
fernet = Fernet("SECRET")
encrypted_key = fernet.encrypt("KEY".encode())
```
Insert result without the begining b' and end '.

**Comment by iFargle** [comment]
Sounds like I need to do more checking in load_checks() - https://github.com/iFargle/headscale-webui/blob/0818d70543d89c62766fa786b3860bf5e2fe4f2f/helper.py#L269 

I'll see if I can get this fixed up later today.
