### ISSUE TITLE
Adding pre-auth keys does not work.

### ISSUE THREAD

**Issue by apollo13** [iFargle/headscale-webui#38]
When I try to add a pre-auth key an empty window pops up and nothing happens:
![image](https://user-images.githubusercontent.com/81547/222774769-7711fc95-c40e-42ee-a8f5-fbc0d0c3d9b6.png)

The js console & server logs show no issues.

**Comment by iFargle** [comment]
Same issue.  I'll get it fixed shortly!

**Comment by iFargle** [comment]
Fixed :) thanks for pointing this out!

**Comment by apollo13** [comment]
Hi @iFargle, thank you for the fix. I see that you are using `+` operations to concat strings to construct HTML. An attacker can use this to inject other HTML or Javascript (consider someone setting a `user_name` to `<b>apollo13</b>` which would show up as bold). Granted the username per se is a bad example because headscale itself might forbid such usernames. Nevertheless, why open yourself for a potential vulnerability in a security sensitive UI. If you were to use Jinja for templating with escaping enabled you'd at least fix 90% of such issues.

**Comment by iFargle** [comment]
Interesting... 
I'm very new to programming.  I'll take all the help I can get!  I'll look into this.  If I can figure it out I'll push some fixes.  Thank you!

**Comment by apollo13** [comment]
That is a great attitude! Feel free to tag me on PR where you want some reviews, I cannot always answer in a timely manner but I'll try 😊
