### ISSUE TITLE
Publish arm64 image to Docker Hub 

### ISSUE THREAD

**Issue by xiaolei0125** [iFargle/headscale-webui#40]
Can you build arm64 arch docker image, and publish to Docker Hub ?   Thanks!

**Comment by iFargle** [comment]
I'll try.  Not super familiar with multiarch and all that.  I'll test some tonight!

**Comment by iFargle** [comment]
Try `ifargle/headscale-webui:manual`
If that works I'll push it to main :)

**Comment by xiaolei0125** [comment]
@iFargle   The ifargle/headscale-webui:manual image can work on arm64 system,  Thank you!

**Comment by iFargle** [comment]
it's building.  The main branch will be up in an hour or so.  Insignificant changes from the version you're running.
