### ISSUE TITLE
Unknown Manifest when pulling ghcr container

### ISSUE THREAD

**Issue by iFargle** [iFargle/headscale-webui#48]

**Comment by iFargle** [comment]
Repushed.  Looks good now

**Comment by BlueHairMinerBoy** [comment]
FYI this has happened again - have pulled from Docker Hub and it works fine now

**Comment by iFargle** [comment]
I think this is caused by the clean untagged builds action.  I'm going to disable it and re-run.

**Comment by iFargle** [comment]
Yep, that looks to have solved the problem.
