### ISSUE TITLE
Embeded DERP is configured but information is not visible in overview

### ISSUE THREAD

**Issue by muchachagrande** [iFargle/headscale-webui#52]
Hi,
I have the DERP server configured, but the information is not visible on the overview DERP section.
I think I found the problem on renderer.py at line 107. The "enabled" attribute is tested as a string, but is a boolean, so True must be written without double quotes.
Thank you and cheers

**Comment by iFargle** [comment]
Thanks!
New build will be out in an hour or so (these multiarch builds take a while)
