### ISSUE TITLE
Server URL shown on "add machine to Headscale" is the internal URL

### ISSUE THREAD

**Issue by muchachagrande** [iFargle/headscale-webui#53]
When I select "add machine to URL" the explanation to use Tailscale is showing the Headscale URL set at HS_SERVER enviroment variable.
The problem is that this URL is the internal connection I set between headscale and headscale-webui containers (http://192.168.2.5:8088).
May be it is better to use the URL taken from config.yaml. That is actually being shown in the overview page. The server_url variable.

**Comment by iFargle** [comment]
Good point.  I'll do this in v0.6.0 (inpage-search branch) :)  Should be ready in a week or so

**Comment by iFargle** [comment]
Closing -- Fixes will be in main in about 1.5 hours (multiarch builds take a while). Please use the main branch after it's available.

Thanks!
