### ISSUE TITLE
Subnet Routing Failover

### ISSUE THREAD

**Issue by drag0n141** [iFargle/headscale-webui#54]
Is it planned to add the subnet failover function to the webui?

https://github.com/juanfont/headscale/pull/1024

**Comment by iFargle** [comment]
I'll give it a shot :)

**Comment by iFargle** [comment]
So it doesn't look like there's a way to do this via the builtin API, other than enabling / disabling routes in a certain order to determine which is primary.

As of now, it looks like if you just enable the route on two nodes it "just works" -- Do you need to be able to select which is primary?

**Comment by iFargle** [comment]
I can also add an indicator of route failover if that would be beneficial

**Comment by drag0n141** [comment]
> As of now, it looks like if you just enable the route on two nodes it "just works" -- Do you need to be able to select which is primary?

Yes correctly :) but dont know i that is possible i am not using the routing failover at the moment.

> I can also add an indicator of route failover if that would be beneficial

I think that would help.

**Comment by iFargle** [comment]
It's technically possible -- I'll see what I can do!  I'm working on rewriting how I manage routes so once that's done I"ll work on this

**Comment by iFargle** [comment]
I've added some preliminary work into v0.6.0
You can test with `ghcr.io/ifargle/headscale-webui:testing` right now if you'd like to try it out

**Comment by drag0n141** [comment]
I have installed the :testing version. Now all Routes are duplicated. One normal Route and one as "Failover Pair"

**Comment by iFargle** [comment]
Interesting...
All routes, including the exit routes?

**Comment by iFargle** [comment]
Can you give examples of the failover ranges you are using?
All I'm doing right now is a simple list search to determine if there are duplicate IP's:
https://github.com/iFargle/headscale-webui/blob/fc5908f3e2dba26d96756e9242babd2b63226bab/renderer.py#L307-L332

**Comment by iFargle** [comment]
Oh I see the issue..
https://github.com/iFargle/headscale-webui/blob/fc5908f3e2dba26d96756e9242babd2b63226bab/renderer.py#L313

I've pushed anew build.  Let me know if you still see duplicates

**Comment by drag0n141** [comment]
Now it looks good no more duplicates :)

![image](https://user-images.githubusercontent.com/44865095/227125406-e0a1489a-683f-44ee-b92e-934d94d20b97.png)

**Comment by iFargle** [comment]
Perfect!  
They're colored based on their pair.   I think I'm going to add a routes page to this release.  I'll see if I have time

**Comment by iFargle** [comment]
btw don't use testing for long -- I am always pushing updates to it so things will break all the time.  Or just use this current release of testing until I push it to main :)

**Comment by iFargle** [comment]
Back at it this week.  Made some good improvements in the testing build
![image](https://user-images.githubusercontent.com/124551390/228403809-38b3b343-6f60-4a1e-b07a-7db450050767.png)

Once I finish the code up for better enabling/disabling of these routes it will be pushed to main

**Comment by iFargle** [comment]
Closing -- This will be in main in about 1.5 hours (multiarch builds take a while). Please use the main branch after it's available.

Thanks!
