### ISSUE TITLE
Unknown Manifest error

### ISSUE THREAD

**Issue by hibare** [iFargle/headscale-webui#59]
Docker pull is resulting in following error

```shell
❯ docker pull ghcr.io/ifargle/headscale-webui:latest
v0.5.5: Pulling from ifargle/headscale-webui
manifest unknown
```

Tested it on different machines across different geographic locations

**Comment by iFargle** [comment]
Interesting... Latest version is v0.5.6.

I'll look into it.

**Comment by iFargle** [comment]
Yeah same issue here...
I really don't understand why this keeps happening.
I'm running another build.  It will be up in 45 minutes or so!

For now, you can pull the docker hub image.  It's the same `ifargle/headscale-webui`

**Comment by iFargle** [comment]
Fixed (again)
Sorry about that!
