### ISSUE TITLE
always suck at Loading basic auth libraries and configuring app...

### ISSUE THREAD

**Issue by bidabrain** [iFargle/headscale-webui#60]
# docker compose up

[+] Running 1/1
 ⠿ Container headscale-webui  Created                                     0.2s
Attaching to headscale-webui
headscale-webui  | [2023-03-25 11:51:46 +0800] [1] [INFO] Starting gunicorn 20.1.0
headscale-webui  | [2023-03-25 11:51:46 +0800] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
headscale-webui  | [2023-03-25 11:51:46 +0800] [1] [INFO] Using worker: sync
headscale-webui  | [2023-03-25 11:51:46 +0800] [8] [INFO] Booting worker with pid: 8
headscale-webui  | [2023-03-25 11:51:49,126] INFO in server: Headscale-WebUI Version:  v0.5.6 / main
headscale-webui  | [2023-03-25 11:51:49,126] INFO in server: LOG LEVEL SET TO DEBUG
headscale-webui  | [2023-03-25 11:51:49,126] INFO in server: DEBUG STATE:  True
headscale-webui  | [2023-03-25 11:51:49,127] INFO in server: Loading basic auth libraries and configuring app...

**Comment by iFargle** [comment]
Any errors when you try to navigate to a page?

On March 25, 2023 3:53:05 AM UTC, bidabrain ***@***.***> wrote:
># docker compose up
>
>[+] Running 1/1
> ⠿ Container headscale-webui  Created                                     0.2s
>Attaching to headscale-webui
>headscale-webui  | [2023-03-25 11:51:46 +0800] [1] [INFO] Starting gunicorn 20.1.0
>headscale-webui  | [2023-03-25 11:51:46 +0800] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
>headscale-webui  | [2023-03-25 11:51:46 +0800] [1] [INFO] Using worker: sync
>headscale-webui  | [2023-03-25 11:51:46 +0800] [8] [INFO] Booting worker with pid: 8
>headscale-webui  | [2023-03-25 11:51:49,126] INFO in server: Headscale-WebUI Version:  v0.5.6 / main
>headscale-webui  | [2023-03-25 11:51:49,126] INFO in server: LOG LEVEL SET TO DEBUG
>headscale-webui  | [2023-03-25 11:51:49,126] INFO in server: DEBUG STATE:  True
>headscale-webui  | [2023-03-25 11:51:49,127] INFO in server: Loading basic auth libraries and configuring app...
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/iFargle/headscale-webui/issues/60
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Albert J. Copeland
***@***.***
PGP Fingerprint:  64F6C4EB46C4543A

**Comment by bidabrain** [comment]
> Any errors when you try to navigate to a page?
> On March 25, 2023 3:53:05 AM UTC, bidabrain ***@***.***> wrote: # docker compose up [+] Running 1/1 ⠿ Container headscale-webui Created 0.2s Attaching to headscale-webui headscale-webui | [2023-03-25 11:51:46 +0800] [1] [INFO] Starting gunicorn 20.1.0 headscale-webui | [2023-03-25 11:51:46 +0800] [1] [INFO] Listening at: http://0.0.0.0:5000 (1) headscale-webui | [2023-03-25 11:51:46 +0800] [1] [INFO] Using worker: sync headscale-webui | [2023-03-25 11:51:46 +0800] [8] [INFO] Booting worker with pid: 8 headscale-webui | [2023-03-25 11:51:49,126] INFO in server: Headscale-WebUI Version: v0.5.6 / main headscale-webui | [2023-03-25 11:51:49,126] INFO in server: LOG LEVEL SET TO DEBUG headscale-webui | [2023-03-25 11:51:49,126] INFO in server: DEBUG STATE: True headscale-webui | [2023-03-25 11:51:49,127] INFO in server: Loading basic auth libraries and configuring app... -- Reply to this email directly or view it on GitHub: #60 You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>
> -- Albert J. Copeland ***@***.*** PGP Fingerprint:  64F6C4EB46C4543A

after docker compose run.  the container simply can not even successfully run. I enabled the debug , but log stuck at this point and no more information shows

headscale-webui  | [2023-03-25 13:16:23,744] INFO in server: DEBUG STATE:  True
headscale-webui  | [2023-03-25 13:16:23,745] INFO in server: Loading basic auth libraries and configuring app...

**Comment by iFargle** [comment]
Yes that looks normal to me.  When you start loading pages it will output more into 

On March 25, 2023 4:18:22 AM UTC, bidabrain ***@***.***> wrote:
>> Any errors when you try to navigate to a page?
>> On March 25, 2023 3:53:05 AM UTC, bidabrain ***@***.***> wrote: # docker compose up [+] Running 1/1 ⠿ Container headscale-webui Created 0.2s Attaching to headscale-webui headscale-webui | [2023-03-25 11:51:46 +0800] [1] [INFO] Starting gunicorn 20.1.0 headscale-webui | [2023-03-25 11:51:46 +0800] [1] [INFO] Listening at: http://0.0.0.0:5000 (1) headscale-webui | [2023-03-25 11:51:46 +0800] [1] [INFO] Using worker: sync headscale-webui | [2023-03-25 11:51:46 +0800] [8] [INFO] Booting worker with pid: 8 headscale-webui | [2023-03-25 11:51:49,126] INFO in server: Headscale-WebUI Version: v0.5.6 / main headscale-webui | [2023-03-25 11:51:49,126] INFO in server: LOG LEVEL SET TO DEBUG headscale-webui | [2023-03-25 11:51:49,126] INFO in server: DEBUG STATE: True headscale-webui | [2023-03-25 11:51:49,127] INFO in server: Loading basic auth libraries and configuring app... -- Reply to this email directly or view it on GitHub: #60 You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>
>> -- Albert J. Copeland ***@***.*** PGP Fingerprint:  64F6C4EB46C4543A
>
>after docker compose run.  the container simply can not even successfully run. I enabled the debug , but log stuck at this point and no more information shows
>
>headscale-webui  | [2023-03-25 13:16:23,744] INFO in server: DEBUG STATE:  True
>headscale-webui  | [2023-03-25 13:16:23,745] INFO in server: Loading basic auth libraries and configuring app...
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/iFargle/headscale-webui/issues/60#issuecomment-1483715233
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Albert J. Copeland
***@***.***
PGP Fingerprint:  64F6C4EB46C4543A

**Comment by bidabrain** [comment]
how I can change the default 5000 port to other port?

**Comment by iFargle** [comment]
You can use:
```
ports:
  - 127.0.0.1:<externalPort>:5000
```
Or just 
```
ports:
  - <externalPort>:5000
```
to access from outside the host

**Comment by inlophe** [comment]
```
[2023-03-25 12:03:28 +0700] [1] [INFO] Starting gunicorn 20.1.0
[2023-03-25 12:03:28 +0700] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2023-03-25 12:03:28 +0700] [1] [INFO] Using worker: sync
[2023-03-25 12:03:28 +0700] [8] [INFO] Booting worker with pid: 8
[2023-03-25 12:03:30,351] INFO in server: Headscale-WebUI Version:  v0.5.6 / main
[2023-03-25 12:03:30,351] INFO in server: LOG LEVEL SET TO DEBUG
[2023-03-25 12:03:30,351] INFO in server: DEBUG STATE:  True
[2023-03-25 12:03:30,352] INFO in server: Loading basic auth libraries and configuring app...
[2023-03-25 12:06:38 +0700] [1] [CRITICAL] WORKER TIMEOUT (pid:8)
[2023-03-25 12:06:38 +0700] [8] [INFO] Worker exiting (pid: 8)
[2023-03-25 12:06:38 +0700] [9] [INFO] Booting worker with pid: 9
[2023-03-25 12:06:39,526] INFO in server: Headscale-WebUI Version:  v0.5.6 / main
[2023-03-25 12:06:39,526] INFO in server: LOG LEVEL SET TO DEBUG
[2023-03-25 12:06:39,527] INFO in server: DEBUG STATE:  True
[2023-03-25 12:06:39,527] INFO in server: Loading basic auth libraries and configuring app...
```

Just tried today and keep getting bad gateway when trying to access the webui. Everytime I tried to access the URL, I always got worker exiting in the log.

Any idea what's wrong?

**Comment by iFargle** [comment]
I've created a new thread for you @inlophe #61

**Comment by iFargle** [comment]
@bidabrain  - Is everything working for you now?  Or are you still having issues?
thanks!

**Comment by bidabrain** [comment]
> 

yes. Problem solved. It's simply that 5000 port is occupied. I changed one then everything works. Thanks

**Comment by iFargle** [comment]
Ahh, good to know!
