### ISSUE TITLE
docker image manifest for v0.6.0 is not working

### ISSUE THREAD

**Issue by pridkett** [iFargle/headscale-webui#65]
The latest version that was pushed as v0.6.0 appears to have issues with its manifest. I'm following a process that worked yesterday with the older version and is what should happen according to the [headscale-webui package page](https://github.com/ifargle/headscale-webui/pkgs/container/headscale-webui).

```
$ docker pull ghcr.io/ifargle/headscale-webui:latest
latest: Pulling from ifargle/headscale-webui
manifest unknown
$ docker pull ghcr.io/ifargle/headscale-webui:v0.6.0
v0.6.0: Pulling from ifargle/headscale-webui
manifest unknown
```

This might just mean that the image needs to be pushed again.

Tested on amd64-linux, amd64-wsl, arm-macos, arm-linux. Same responses all around. Does not appear to be a widespread ghcr.io issue as I can pull other images.

**Comment by iFargle** [comment]
Ugh :( I don't know why this happens.  I even test a pull in the Jenkins build after it pushes. 

I'll repush. The docker hub image is fine if you want to use that. 

On March 30, 2023 3:23:55 PM UTC, Patrick Wagstrom ***@***.***> wrote:
>The latest version that was pushed as v0.6.0 appears to have issues with its manifest. I'm following a process that worked yesterday with the older version and is what should happen according to the [headscale-webui package page](https://github.com/ifargle/headscale-webui/pkgs/container/headscale-webui).
>
>```
>$ docker pull ghcr.io/ifargle/headscale-webui:latest
>latest: Pulling from ifargle/headscale-webui
>manifest unknown
>$ docker pull ghcr.io/ifargle/headscale-webui:v0.6.0
>v0.6.0: Pulling from ifargle/headscale-webui
>manifest unknown
>```
>
>This might just mean that the image needs to be pushed again.
>
>Tested on amd64-linux, amd64-wsl, arm-macos, arm-linux. Same responses all around. Does not appear to be a widespread ghcr.io issue as I can pull other images.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/iFargle/headscale-webui/issues/65
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Albert J. Copeland
***@***.***
PGP Fingerprint:  64F6C4EB46C4543A

**Comment by iFargle** [comment]
Ok.  Build is finished.  Can you try :latest and :v0.6.0 again?

**Comment by pridkett** [comment]
The new build works. Thanks for fixing it. I'm going to close this issue.

Also, thanks for a genuinely useful tool.

**Comment by iFargle** [comment]
Let me know if you have any issues or have any feature requests you'd like to see!  I develop this in my free time as a personal project so I'm always willing to add more features if they're useful!
