### ISSUE TITLE
Experience optimization for 'add machine'

### ISSUE THREAD

**Issue by threerog** [iFargle/headscale-webui#81]
Experience optimization for 'add machine'

I'm not sure if it's just an individual phenomenon
When I added a machine on the webui and clicked on "add machine", the "add machine" panel did not automatically close, and the machine list did not automatically refresh, requiring manual refresh every time.

**Comment by iFargle** [comment]
Yeah it could definitely be improved.  I didn't do a lot of testing on it since I use OIDC:
https://github.com/iFargle/headscale-webui/blob/3934c3b2cf94da068fccc0855be138e7b738ad48/static/js/custom.js#L653-L676

You are more than welcome to submit a pull request to improve this :)

**Comment by iFargle** [comment]
Thank you :)
