### ISSUE TITLE
Container not working with docker volume

### ISSUE THREAD

**Issue by acul009** [iFargle/headscale-webui#97]
Hi,
I cant get the container to work. It keeps giving me this error:
`/data is not writable. Please ensure your permissions are correct. /data mount should be writable by UID/GID 1000:1000.`

I'm using docker volumes, not bind mounts. These should theoretically take on the right permissions.

From what I could gather, it should be enough to create the /data folder and chown it to the currect user in the dockerfile.

**Comment by iFargle** [comment]
Give me a bit, I"ll try this :)

**Comment by iFargle** [comment]
Can you pull latest?  Let me know if it works?

**Comment by iFargle** [comment]
Let me know if this is still an issue.
