### ISSUE TITLE
What are the specific functions of Ephemeral in PreAuthKey

### ISSUE THREAD

**Issue by threerog** [iFargle/headscale-webui#99]
What is the specific function of Ephemeral in PreAuthKey? The description is too simple, which makes me have the same illusion as the Reusable attribute

**Comment by iFargle** [comment]
An Ephemeral node will disappear from headscale entirely.  A reusable key can be used multiple times and those machines will not be removed, unless the key is also ephemeral. 
 

On May 2, 2023 7:32:59 AM UTC, threerog ***@***.***> wrote:
>What is the specific function of Ephemeral in PreAuthKey? The description is too simple, which makes me have the same illusion as the Reusable attribute
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/iFargle/headscale-webui/issues/99
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Albert J. Copeland
***@***.***
PGP Fingerprint:  64F6C4EB46C4543A

**Comment by threerog** [comment]
Thank you, I understand
